echo -n "" > distances_points.txt
echo -n "rotatedpi8_v0.3s0.4v0.3s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.3s0.4v0.3s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.3s0.63v0.3s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.3s0.63v0.3s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.3s0.87v0.3s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.3s0.87v0.3s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.3s1.1v0.3s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.3s1.1v0.3s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.3s1.33v0.3s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.3s1.33v0.3s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.3s1.57v0.3s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.3s1.57v0.3s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.3s1.8v0.3s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.3s1.8v0.3s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.3s2.03v0.3s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.3s2.03v0.3s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.3s2.27v0.3s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.3s2.27v0.3s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.3s2.5v0.3s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.3s2.5v0.3s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.33s0.4v0.33s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.33s0.4v0.33s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.33s0.63v0.33s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.33s0.63v0.33s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.33s0.87v0.33s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.33s0.87v0.33s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.33s1.1v0.33s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.33s1.1v0.33s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.33s1.33v0.33s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.33s1.33v0.33s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.33s1.57v0.33s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.33s1.57v0.33s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.33s1.8v0.33s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.33s1.8v0.33s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.33s2.03v0.33s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.33s2.03v0.33s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.33s2.27v0.33s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.33s2.27v0.33s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.33s2.5v0.33s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.33s2.5v0.33s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.35s0.4v0.35s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.35s0.4v0.35s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.35s0.63v0.35s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.35s0.63v0.35s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.35s0.87v0.35s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.35s0.87v0.35s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.35s1.1v0.35s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.35s1.1v0.35s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.35s1.33v0.35s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.35s1.33v0.35s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.35s1.57v0.35s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.35s1.57v0.35s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.35s1.8v0.35s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.35s1.8v0.35s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.35s2.03v0.35s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.35s2.03v0.35s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.35s2.27v0.35s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.35s2.27v0.35s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.35s2.5v0.35s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.35s2.5v0.35s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.38s0.4v0.38s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.38s0.4v0.38s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.38s0.63v0.38s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.38s0.63v0.38s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.38s0.87v0.38s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.38s0.87v0.38s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.38s1.1v0.38s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.38s1.1v0.38s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.38s1.33v0.38s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.38s1.33v0.38s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.38s1.57v0.38s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.38s1.57v0.38s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.38s1.8v0.38s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.38s1.8v0.38s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.38s2.03v0.38s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.38s2.03v0.38s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.38s2.27v0.38s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.38s2.27v0.38s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.38s2.5v0.38s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.38s2.5v0.38s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.4s0.4v0.4s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.4s0.4v0.4s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.4s0.63v0.4s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.4s0.63v0.4s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.4s0.87v0.4s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.4s0.87v0.4s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.4s1.1v0.4s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.4s1.1v0.4s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.4s1.33v0.4s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.4s1.33v0.4s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.4s1.57v0.4s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.4s1.57v0.4s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.4s1.8v0.4s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.4s1.8v0.4s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.4s2.03v0.4s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.4s2.03v0.4s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.4s2.27v0.4s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.4s2.27v0.4s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v0.4s2.5v0.4s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v0.4s2.5v0.4s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.3s0.4v0.3s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.3s0.4v0.3s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.3s0.63v0.3s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.3s0.63v0.3s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.3s0.87v0.3s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.3s0.87v0.3s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.3s1.1v0.3s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.3s1.1v0.3s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.3s1.33v0.3s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.3s1.33v0.3s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.3s1.57v0.3s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.3s1.57v0.3s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.3s1.8v0.3s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.3s1.8v0.3s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.3s2.03v0.3s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.3s2.03v0.3s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.3s2.27v0.3s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.3s2.27v0.3s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.3s2.5v0.3s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.3s2.5v0.3s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.33s0.4v0.33s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.33s0.4v0.33s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.33s0.63v0.33s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.33s0.63v0.33s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.33s0.87v0.33s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.33s0.87v0.33s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.33s1.1v0.33s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.33s1.1v0.33s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.33s1.33v0.33s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.33s1.33v0.33s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.33s1.57v0.33s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.33s1.57v0.33s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.33s1.8v0.33s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.33s1.8v0.33s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.33s2.03v0.33s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.33s2.03v0.33s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.33s2.27v0.33s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.33s2.27v0.33s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.33s2.5v0.33s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.33s2.5v0.33s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.35s0.4v0.35s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.35s0.4v0.35s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.35s0.63v0.35s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.35s0.63v0.35s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.35s0.87v0.35s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.35s0.87v0.35s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.35s1.1v0.35s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.35s1.1v0.35s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.35s1.33v0.35s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.35s1.33v0.35s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.35s1.57v0.35s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.35s1.57v0.35s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.35s1.8v0.35s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.35s1.8v0.35s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.35s2.03v0.35s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.35s2.03v0.35s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.35s2.27v0.35s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.35s2.27v0.35s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.35s2.5v0.35s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.35s2.5v0.35s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.38s0.4v0.38s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.38s0.4v0.38s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.38s0.63v0.38s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.38s0.63v0.38s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.38s0.87v0.38s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.38s0.87v0.38s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.38s1.1v0.38s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.38s1.1v0.38s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.38s1.33v0.38s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.38s1.33v0.38s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.38s1.57v0.38s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.38s1.57v0.38s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.38s1.8v0.38s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.38s1.8v0.38s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.38s2.03v0.38s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.38s2.03v0.38s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.38s2.27v0.38s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.38s2.27v0.38s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.38s2.5v0.38s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.38s2.5v0.38s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.4s0.4v0.4s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.4s0.4v0.4s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.4s0.63v0.4s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.4s0.63v0.4s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.4s0.87v0.4s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.4s0.87v0.4s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.4s1.1v0.4s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.4s1.1v0.4s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.4s1.33v0.4s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.4s1.33v0.4s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.4s1.57v0.4s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.4s1.57v0.4s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.4s1.8v0.4s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.4s1.8v0.4s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.4s2.03v0.4s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.4s2.03v0.4s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.4s2.27v0.4s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.4s2.27v0.4s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v0.4s2.5v0.4s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v0.4s2.5v0.4s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_rotatedpi4.pcd >> distances_points.txt
echo -n "translated10_v0.3s0.4v0.3s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.3s0.4v0.3s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.3s0.63v0.3s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.3s0.63v0.3s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.3s0.87v0.3s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.3s0.87v0.3s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.3s1.1v0.3s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.3s1.1v0.3s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.3s1.33v0.3s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.3s1.33v0.3s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.3s1.57v0.3s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.3s1.57v0.3s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.3s1.8v0.3s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.3s1.8v0.3s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.3s2.03v0.3s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.3s2.03v0.3s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.3s2.27v0.3s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.3s2.27v0.3s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.3s2.5v0.3s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.3s2.5v0.3s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.33s0.4v0.33s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.33s0.4v0.33s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.33s0.63v0.33s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.33s0.63v0.33s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.33s0.87v0.33s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.33s0.87v0.33s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.33s1.1v0.33s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.33s1.1v0.33s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.33s1.33v0.33s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.33s1.33v0.33s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.33s1.57v0.33s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.33s1.57v0.33s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.33s1.8v0.33s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.33s1.8v0.33s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.33s2.03v0.33s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.33s2.03v0.33s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.33s2.27v0.33s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.33s2.27v0.33s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.33s2.5v0.33s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.33s2.5v0.33s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.35s0.4v0.35s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.35s0.4v0.35s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.35s0.63v0.35s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.35s0.63v0.35s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.35s0.87v0.35s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.35s0.87v0.35s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.35s1.1v0.35s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.35s1.1v0.35s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.35s1.33v0.35s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.35s1.33v0.35s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.35s1.57v0.35s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.35s1.57v0.35s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.35s1.8v0.35s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.35s1.8v0.35s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.35s2.03v0.35s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.35s2.03v0.35s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.35s2.27v0.35s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.35s2.27v0.35s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.35s2.5v0.35s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.35s2.5v0.35s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.38s0.4v0.38s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.38s0.4v0.38s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.38s0.63v0.38s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.38s0.63v0.38s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.38s0.87v0.38s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.38s0.87v0.38s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.38s1.1v0.38s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.38s1.1v0.38s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.38s1.33v0.38s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.38s1.33v0.38s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.38s1.57v0.38s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.38s1.57v0.38s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.38s1.8v0.38s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.38s1.8v0.38s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.38s2.03v0.38s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.38s2.03v0.38s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.38s2.27v0.38s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.38s2.27v0.38s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.38s2.5v0.38s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.38s2.5v0.38s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.4s0.4v0.4s0.4 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.4s0.4v0.4s0.4.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.4s0.63v0.4s0.63 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.4s0.63v0.4s0.63.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.4s0.87v0.4s0.87 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.4s0.87v0.4s0.87.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.4s1.1v0.4s1.1 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.4s1.1v0.4s1.1.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.4s1.33v0.4s1.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.4s1.33v0.4s1.33.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.4s1.57v0.4s1.57 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.4s1.57v0.4s1.57.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.4s1.8v0.4s1.8 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.4s1.8v0.4s1.8.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.4s2.03v0.4s2.03 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.4s2.03v0.4s2.03.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.4s2.27v0.4s2.27 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.4s2.27v0.4s2.27.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
echo -n "translated10_v0.4s2.5v0.4s2.5 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v0.4s2.5v0.4s2.5.txt pointclouds/nuclei.pcd pointclouds/nuclei_translated10.pcd >> distances_points.txt
