echo -n "" > distances_points.txt
echo -n "rotatedpi8_v3s10v3s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3s10v3s10.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3s13.33v3s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3s13.33v3s13.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3s16.67v3s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3s16.67v3s16.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3s20v3s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3s20v3s20.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3s23.33v3s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3s23.33v3s23.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3s26.67v3s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3s26.67v3s26.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3s30v3s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3s30v3s30.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3s33.33v3s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3s33.33v3s33.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3s36.67v3s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3s36.67v3s36.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3s40v3s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3s40v3s40.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3.5s10v3.5s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3.5s10v3.5s10.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3.5s13.33v3.5s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3.5s13.33v3.5s13.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3.5s16.67v3.5s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3.5s16.67v3.5s16.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3.5s20v3.5s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3.5s20v3.5s20.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3.5s23.33v3.5s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3.5s23.33v3.5s23.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3.5s26.67v3.5s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3.5s26.67v3.5s26.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3.5s30v3.5s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3.5s30v3.5s30.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3.5s33.33v3.5s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3.5s33.33v3.5s33.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3.5s36.67v3.5s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3.5s36.67v3.5s36.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v3.5s40v3.5s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v3.5s40v3.5s40.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4s10v4s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4s10v4s10.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4s13.33v4s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4s13.33v4s13.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4s16.67v4s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4s16.67v4s16.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4s20v4s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4s20v4s20.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4s23.33v4s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4s23.33v4s23.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4s26.67v4s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4s26.67v4s26.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4s30v4s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4s30v4s30.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4s33.33v4s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4s33.33v4s33.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4s36.67v4s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4s36.67v4s36.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4s40v4s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4s40v4s40.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4.5s10v4.5s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4.5s10v4.5s10.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4.5s13.33v4.5s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4.5s13.33v4.5s13.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4.5s16.67v4.5s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4.5s16.67v4.5s16.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4.5s20v4.5s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4.5s20v4.5s20.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4.5s23.33v4.5s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4.5s23.33v4.5s23.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4.5s26.67v4.5s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4.5s26.67v4.5s26.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4.5s30v4.5s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4.5s30v4.5s30.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4.5s33.33v4.5s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4.5s33.33v4.5s33.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4.5s36.67v4.5s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4.5s36.67v4.5s36.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v4.5s40v4.5s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v4.5s40v4.5s40.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v5s10v5s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v5s10v5s10.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v5s13.33v5s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v5s13.33v5s13.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v5s16.67v5s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v5s16.67v5s16.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v5s20v5s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v5s20v5s20.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v5s23.33v5s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v5s23.33v5s23.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v5s26.67v5s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v5s26.67v5s26.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v5s30v5s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v5s30v5s30.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v5s33.33v5s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v5s33.33v5s33.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v5s36.67v5s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v5s36.67v5s36.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi8_v5s40v5s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi8_v5s40v5s40.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi8.pcd >> distances_points.txt
echo -n "rotatedpi4_v3s10v3s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3s10v3s10.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3s13.33v3s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3s13.33v3s13.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3s16.67v3s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3s16.67v3s16.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3s20v3s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3s20v3s20.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3s23.33v3s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3s23.33v3s23.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3s26.67v3s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3s26.67v3s26.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3s30v3s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3s30v3s30.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3s33.33v3s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3s33.33v3s33.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3s36.67v3s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3s36.67v3s36.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3s40v3s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3s40v3s40.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3.5s10v3.5s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3.5s10v3.5s10.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3.5s13.33v3.5s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3.5s13.33v3.5s13.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3.5s16.67v3.5s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3.5s16.67v3.5s16.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3.5s20v3.5s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3.5s20v3.5s20.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3.5s23.33v3.5s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3.5s23.33v3.5s23.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3.5s26.67v3.5s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3.5s26.67v3.5s26.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3.5s30v3.5s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3.5s30v3.5s30.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3.5s33.33v3.5s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3.5s33.33v3.5s33.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3.5s36.67v3.5s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3.5s36.67v3.5s36.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v3.5s40v3.5s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v3.5s40v3.5s40.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4s10v4s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4s10v4s10.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4s13.33v4s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4s13.33v4s13.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4s16.67v4s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4s16.67v4s16.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4s20v4s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4s20v4s20.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4s23.33v4s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4s23.33v4s23.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4s26.67v4s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4s26.67v4s26.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4s30v4s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4s30v4s30.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4s33.33v4s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4s33.33v4s33.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4s36.67v4s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4s36.67v4s36.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4s40v4s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4s40v4s40.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4.5s10v4.5s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4.5s10v4.5s10.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4.5s13.33v4.5s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4.5s13.33v4.5s13.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4.5s16.67v4.5s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4.5s16.67v4.5s16.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4.5s20v4.5s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4.5s20v4.5s20.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4.5s23.33v4.5s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4.5s23.33v4.5s23.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4.5s26.67v4.5s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4.5s26.67v4.5s26.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4.5s30v4.5s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4.5s30v4.5s30.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4.5s33.33v4.5s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4.5s33.33v4.5s33.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4.5s36.67v4.5s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4.5s36.67v4.5s36.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v4.5s40v4.5s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v4.5s40v4.5s40.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v5s10v5s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v5s10v5s10.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v5s13.33v5s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v5s13.33v5s13.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v5s16.67v5s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v5s16.67v5s16.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v5s20v5s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v5s20v5s20.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v5s23.33v5s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v5s23.33v5s23.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v5s26.67v5s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v5s26.67v5s26.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v5s30v5s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v5s30v5s30.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v5s33.33v5s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v5s33.33v5s33.33.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v5s36.67v5s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v5s36.67v5s36.67.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "rotatedpi4_v5s40v5s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//rotatedpi4_v5s40v5s40.txt pointclouds/valve.pcd pointclouds/valve_rotatedpi4.pcd >> distances_points.txt
echo -n "translated10_v3s10v3s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3s10v3s10.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3s13.33v3s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3s13.33v3s13.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3s16.67v3s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3s16.67v3s16.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3s20v3s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3s20v3s20.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3s23.33v3s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3s23.33v3s23.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3s26.67v3s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3s26.67v3s26.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3s30v3s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3s30v3s30.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3s33.33v3s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3s33.33v3s33.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3s36.67v3s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3s36.67v3s36.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3s40v3s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3s40v3s40.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3.5s10v3.5s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3.5s10v3.5s10.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3.5s13.33v3.5s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3.5s13.33v3.5s13.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3.5s16.67v3.5s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3.5s16.67v3.5s16.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3.5s20v3.5s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3.5s20v3.5s20.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3.5s23.33v3.5s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3.5s23.33v3.5s23.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3.5s26.67v3.5s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3.5s26.67v3.5s26.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3.5s30v3.5s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3.5s30v3.5s30.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3.5s33.33v3.5s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3.5s33.33v3.5s33.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3.5s36.67v3.5s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3.5s36.67v3.5s36.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v3.5s40v3.5s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v3.5s40v3.5s40.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4s10v4s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4s10v4s10.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4s13.33v4s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4s13.33v4s13.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4s16.67v4s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4s16.67v4s16.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4s20v4s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4s20v4s20.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4s23.33v4s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4s23.33v4s23.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4s26.67v4s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4s26.67v4s26.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4s30v4s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4s30v4s30.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4s33.33v4s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4s33.33v4s33.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4s36.67v4s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4s36.67v4s36.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4s40v4s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4s40v4s40.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4.5s10v4.5s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4.5s10v4.5s10.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4.5s13.33v4.5s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4.5s13.33v4.5s13.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4.5s16.67v4.5s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4.5s16.67v4.5s16.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4.5s20v4.5s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4.5s20v4.5s20.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4.5s23.33v4.5s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4.5s23.33v4.5s23.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4.5s26.67v4.5s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4.5s26.67v4.5s26.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4.5s30v4.5s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4.5s30v4.5s30.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4.5s33.33v4.5s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4.5s33.33v4.5s33.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4.5s36.67v4.5s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4.5s36.67v4.5s36.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v4.5s40v4.5s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v4.5s40v4.5s40.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v5s10v5s10 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v5s10v5s10.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v5s13.33v5s13.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v5s13.33v5s13.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v5s16.67v5s16.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v5s16.67v5s16.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v5s20v5s20 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v5s20v5s20.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v5s23.33v5s23.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v5s23.33v5s23.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v5s26.67v5s26.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v5s26.67v5s26.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v5s30v5s30 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v5s30v5s30.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v5s33.33v5s33.33 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v5s33.33v5s33.33.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v5s36.67v5s36.67 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v5s36.67v5s36.67.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
echo -n "translated10_v5s40v5s40 " >> distances_points.txt
../../../scripts_python/distance_matched_pointclouds_pcd.py transforms//translated10_v5s40v5s40.txt pointclouds/valve.pcd pointclouds/valve_translated10.pcd >> distances_points.txt
